// Date: 5/18/2015 4:06:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.internetcraft.Entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDoge extends ModelBase
{
  //fields
    ModelRenderer WolfHead;
    ModelRenderer Body;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Tail;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
  
  	public ModelDoge()
  {
    textureWidth = 64;
    textureHeight = 32;

	  this.WolfHead = new ModelRenderer(this, 0, 0);
	  this.WolfHead.addBox(-3F, -3F, -2F, 6, 6, 4);
	  this.WolfHead.setRotationPoint(-1F, 13.5F, -1.9F);

	  this.Body = new ModelRenderer(this, 40, 17);
	  this.Body.addBox(-4F, -2F, -3F, 6, 9, 6);
	  this.Body.setRotationPoint(0F, 14F, 2F);

	  this.Leg1 = new ModelRenderer(this, 0, 22);
	  this.Leg1.addBox(-1F, 0F, -1F, 2, 8, 2);
	  this.Leg1.setRotationPoint(-2.5F, 16F, 7F);

	  this.Leg2 = new ModelRenderer(this, 10, 22);
	  this.Leg2.addBox(-1F, 0F, -1F, 2, 8, 2);
	  this.Leg2.setRotationPoint(0.5F, 16F, 7F);

	  this.Leg3 = new ModelRenderer(this, 30, 22);
	  this.Leg3.addBox(-1F, 0F, -1F, 2, 8, 2);
	  this.Leg3.setRotationPoint(-2.5F, 16F, 1F);

	  this.Leg4 = new ModelRenderer(this, 20, 22);
	  this.Leg4.addBox(-1F, 0F, -1F, 2, 8, 2);
	  this.Leg4.setRotationPoint(0.5F, 16F, 1F);

	  this.Tail = new ModelRenderer(this, 20, 0);
	  this.Tail.addBox(-1F, 0F, -1F, 2, 8, 2);
	  this.Tail.setRotationPoint(-1F, 12F, 8F);

	  this.Ear1 = new ModelRenderer(this, 58, 0);
	  this.Ear1.addBox(-3F, -5F, 0F, 2, 2, 1);
	  this.Ear1.setRotationPoint(-1F, 13.5F, -2F);

	  this.Ear2 = new ModelRenderer(this, 58, 3);
	  this.Ear2.addBox(1F, -5F, 0F, 2, 2, 1);
	  this.Ear2.setRotationPoint(-1F, 13.5F, -2F);
  }

	public void render(Entity entity, float time, float limbSwing, float p_78088_4_, float headYRot, float headXRot, float yTrans)
	{
		this.setRotationAngles(time, limbSwing, p_78088_4_, headYRot, headXRot, yTrans, entity);

		if(this.isChild)
		{
			float div = 2.0F;

			GlStateManager.pushMatrix();
			GlStateManager.scale(1.0F / div, 1.0F / div, 1.0F / div);
			GlStateManager.translate(0.0F, 24.0F * yTrans, 0.0F);

			this.WolfHead.render(yTrans);
			this.Body.render(yTrans);
			this.Leg1.render(yTrans);
			this.Leg2.render(yTrans);
			this.Leg3.render(yTrans);
			this.Leg4.render(yTrans);
			this.Tail.render(yTrans);
			this.Ear1.render(yTrans);
			this.Ear2.render(yTrans);
			GlStateManager.popMatrix();
		}
		else
		{
			this.WolfHead.render(yTrans);
			this.Body.render(yTrans);
			this.Leg1.render(yTrans);
			this.Leg2.render(yTrans);
			this.Leg3.render(yTrans);
			this.Leg4.render(yTrans);
			this.Tail.render(yTrans);
			this.Ear1.render(yTrans);
			this.Ear2.render(yTrans);
		}
	}

	public void setRotationAngles(float time, float limbSwing, float p_78087_3_, float headYRot, float headXRot, float p_78087_6_, Entity entity)
	{
		this.WolfHead.rotateAngleX = headXRot / (180F / (float)Math.PI);
		this.WolfHead.rotateAngleY = headYRot / (180F / (float)Math.PI);

		this.Body.rotateAngleX = ((float)Math.PI / 2);

		this.Leg1.rotateAngleX = MathHelper.cos(time * 0.6662F) * 1.4F * limbSwing;
		this.Leg2.rotateAngleX = MathHelper.cos(time * 0.6662F + (float)Math.PI) * 1.4F * limbSwing;
		this.Leg3.rotateAngleX = MathHelper.cos(time * 0.6662F + (float)Math.PI) * 1.4F * limbSwing;
		this.Leg4.rotateAngleX = MathHelper.cos(time * 0.6662F) * 1.4F * limbSwing;
	}
}
